### ISSUE TITLE
The virtual database provides a table that contains system information

### ISSUE THREAD

**Issue by alessandrogario** [zeek/zeek-agent#29]
## Table name
host_information

## Schema
| Column name       | Example value                               |
|-------------------|---------------------------------------------|
| os_name           | Linux                                       |
| os_version        | #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 |
| os_release        | 5.3.0-40-generic                            |
| os_machine        | x86_64                                      |
| system_version    | Ubuntu 19.10                                |
| hostname          | hostname.local                              |
| osquery_enabled   | 0                                           |
| uuid              | uuid value                                  |
| broker_version    | 1.2.0-151                                   |
| agent_version     | 1.0.2                                       |

**Comment by rsmmr** [comment]
Looks good. Want to add the agent version as well? And maybe Broker version as well because we allow building with different versions now.

Do we need "bitness"? Not sure if we need it for anything specific, and it's already Implied by architecture.

**Comment by alessandrogario** [comment]
> Looks good. Want to add the agent version as well? And maybe Broker version as well because we allow building with different versions now.

This is a great idea! WIll add the additional columns

> Do we need "bitness"? Not sure if we need it for anything specific, and it's already Implied by architecture.

The architecture column is about the capabilities of the hardware itself, while the bitness is about the software that has been installed on it (i.e.: we can install a 32-bit operating system on an AMD64 processor). I'll remove it if you think it's not a useful detail
