### ISSUE TITLE
 Compiler error on CentOS 7

### ISSUE THREAD

**Issue by Neverlord** [zeek/zeek-agent#5]
I was trying to work on #3, but I cannot build the Zeek Agent. Mac OS seems unsupported at the moment (fails to locate some headers), on Ubuntu I ran into internal compiler errors (this may be because I tried to compile the agent in a Docker container), and on CentOS 7 (using `cmake3` and `devtookit 7`) I see these compiler errors:

```
In file included from ../libraries/audit/src/lib/libaudit.c:47:0:
../libraries/audit/src/lib/libaudit.h:479:8: warning: ISO C forbids zero-size array ‘ctx’ [-Wpedantic]
  char  ctx[0];
        ^~~
../libraries/audit/src/lib/libaudit.c: In function ‘audit_set_backlog_wait_time’:
../libraries/audit/src/lib/libaudit.c:510:20: error: ‘AUDIT_STATUS_BACKLOG_WAIT_TIME’ undeclared (first use in this function); did you mean ‘AUDIT_STATUS_BACKLOG_LIMIT’?
  s.mask          = AUDIT_STATUS_BACKLOG_WAIT_TIME;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    AUDIT_STATUS_BACKLOG_LIMIT
../libraries/audit/src/lib/libaudit.c:510:20: note: each undeclared identifier is reported only once for each function it appears in
../libraries/audit/src/lib/libaudit.c:511:4: error: ‘struct audit_status’ has no member named ‘backlog_wait_time’; did you mean ‘backlog_limit’?
  s.backlog_wait_time = bwt;
    ^~~~~~~~~~~~~~~~~
    backlog_limit
```

Here's the corresponding CMake output:

```
$ cmake3 -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DZEEK_AGENT_ENABLE_INSTALL:BOOL=ON -DZEEK_AGENT_ENABLE_TESTS:BOOL=ON -G Ninja ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- zeek-agent: ccache is not enabled (not found)
-- zeek-agent: Sanitizers are disabled
-- zeek-agent: Tests are enabled
-- Disabling the SQLite R*Tree module
-- Disabling the SQLite FTS extensions
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /users/neverlord/workspace/zeek-agent/build
```

Is CentOS simply not supported or is there something missing in my setup?

**Comment by alessandrogario** [comment]
Hello @Neverlord!

I think that the `linux/audit.h` header is too old compared to the libaudit version we are using (we are currently tracking master in order to include an unreleased memory leak fix inside libauparse).

The officially supported build procedure (i.e. how releases are generated) uses the osquery-toolchain (which, despite the name, is generic and not tied to osquery). This toolchain includes full C++17 support (compiler and C++ library) and the most important thing is that allows us to compile once and run on any Linux distribution that ships glibc >= 2.12.

It is possible to use the osquery-toolchain on CentOS 7 too, and this will fix the issue above since it comes with all the required base system headers/libraries (so that everything is pinned to a known version/configuration on any distro)

**Comment by Neverlord** [comment]
Thanks for the quick response. I'll try again with the osquery toolchain.

**Comment by Neverlord** [comment]
I've managed to compile `zeek-agent` with the `osquery` toolchain and I've also managed to compile and link against current Broker `master` (plus some CMake patches for Broker and CAF).

But how can I tell it's still doing what it's supposed to do? 😅

It seems like there's one test suite, but it's not giving much output for me:

```
$ ./zeek-agent_tests 
===============================================================================
All tests passed (371 assertions in 3 test cases)
```

Before digging into the code myself, are there other test suites or scripts I can run to double-check my patches didn't break something?

**Comment by alessandrogario** [comment]
Hey @Neverlord!

There are no tests on the connection class right now; the most important thing is to check and make sure that Broker/CAF are not importing headers/libraries from the system and are taking everything from the other source-based targets (ldd -d should show what is happening)

**Comment by Neverlord** [comment]
Thank you for your help! I'll close this issue and dig into the `ldd` output.
