### ISSUE TITLE
Request to update pre-built rpm

### ISSUE THREAD

**Issue by scuba-st3v3** [zeek/zeek-agent#60]
When installing the pre-built [rpm](https://github.com/zeek/zeek-agent/releases/download/v1.0.2/zeek30_zeek-agent-1.0.2-1.x86_64.rpm), `/etc/zeek-agent/` is not created by default.  However, this is where the zeek-agent binary expects the configurations to live.

Test box: `CentOS Linux release 7.7.1908 (Core)`
Kernel: `3.10.0-1062.18.1.el7.x86_64`

Would it make sense to put the default config (as referenced [here](https://github.com/zeek/zeek-agent/wiki/Configuration-Guide)) in `/etc/zeek-agent/config.json` during the install process?

**Comment by alessandrogario** [comment]
Hello @scuba-st3v3!

we are about to tag version 1.1.0, which should contain a fix for the problem you are experiencing. 

Would it be possible for you to try out the development packages from the CI artifacts? They can be downloaded from the [status page](https://github.com/zeek/zeek-agent/runs/577664342) by clicking on the **Artifacts** menu on the top right.

It is important to choose the package that matches the Zeek version installed (<= 3.0 or >= 3.1).

**Comment by scuba-st3v3** [comment]
@alessandrogario Looks like you already had this fix!  Sure, here's the test for 3.0.

```
[root@localhost tmp]# rpm -qi zeek-agent
Name        : zeek-agent
Version     : 1.1.0
Release     : 1
Architecture: x86_64
Install Date: Sun Apr 12 14:59:45 2020
Group       : default
Size        : 35610750
License     : unknown
Signature   : (none)
Source RPM  : zeek-agent-1.1.0-1.src.rpm
Build Date  : Fri Apr 10 16:12:04 2020
Build Host  : fv-az50.l14rcsbd23merhttsscekbyvpg.cx.internal.cloudapp.net
Relocations : (not relocatable)
Vendor      : Zeek
URL         : https://zeek.org
Summary     : Zeek Agent is an endpoint monitoring tool that reports system events and data to a Zeek server instance.
Description :
Zeek Agent is an endpoint monitoring tool that reports system events and data to a Zeek server instance.
```
Directory and files are now created

```
[root@localhost]# cd /etc/zeek-agent/
[root@moloch-es zeek-agent]# ls
10-zeek_agent.sample.rules  config.sample.json
```

**Comment by scuba-st3v3** [comment]
For good measure I tested for 3.1 and it provides the same results.

**Comment by alessandrogario** [comment]
> For good measure I tested for 3.1 and it provides the same results.

Thanks for taking the time to test the new packages! :smile:
