### ISSUE TITLE
Cannot build with Ninja

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek-agent#62]
I tried to build 9e0d6bebce4c6ba816d6d1455a738dbbe089df43 with [Ninja](https://ninja-build.org/) on macos in an unparameterized configuration, but this failed since due to a missing dependency.
```
$ mkdir _
$ cmake -GNinja ..
$ ninja
ninja: error: 'libraries/openssl/install/lib/libcrypto.a', needed by 'zeek-agent.app/Contents/MacOS/zeek-agent', missing and no known rule to make it
```

I created a naive fix #61, but this ran into issues on the _macos_build (macOS-10.15, Debug, 3.0)_ build.

**Comment by alessandrogario** [comment]
Hello @bbannier,

thanks for the contribution! We sometimes experience issues with GitHub Actions (workers may disappear before the build is complete). Can you try to re-open the PR so that we can reset the CI tests?

**Comment by bbannier** [comment]
Thanks for having a look @alessandrogario. Reopening the PR indeed passed CI; I can only hope CI produces just false positives, but never false negatives ;)
