### ISSUE TITLE
Build table for associating process with network traffic

### ISSUE THREAD

**Issue by neslog** [zeek/zeek-agent#63]
Goal - have a table that can be queried by Zeek to associate network traffic seen with host process which generated the traffic.  

Use Case - Zeek identifies a network connection associated with an IOC. Zeek then queries zeek-agent to retrieve the process name & md5 along with the parent process.  This will enable enhance detections with additional metadata.

Use Case 2 - Build a new log which contains process information and community-id which can be correlated with other zeek logs to enable hunting and advanced algorithms.

**Comment by alessandrogario** [comment]
A small update, @Wajihulhassan is working on a project that may help to close this issue. I am not able to assign him to the issue (maybe @rsmmr can help?)

**Comment by rsmmr** [comment]
Sent an invite to Wajih to join the repository, you should be able to assign to him once accepted.

**Comment by neslog** [comment]
It would be great to include the parent process details in the table also.  Example, Microsoft Word kicks off a process that generates network traffic.

**Comment by Wajihulhassan** [comment]
Recently merged PRs have added this feature, so I am closing this issue.
